WePlanPlans/WPP_FE

.prettierrc, package.json, pnpm-lock.yaml, postcss.config.js, src/components/common/button/Button.tsx, src/index.css, src/pages/main/main.page.tsx, src/styles/globalStyles.ts, tailwind.config.js
📌 **작업 내용**
폰트 설정, tailwind 기본 설정
공용 Button 컴포넌트 
📌 **확인 사항**
버튼 커스텀 얼마든지 가능합니다
=> Design: tailwind 초기 세팅

src/components/common/footer/Footer.tsx, src/components/common/header/Header.tsx, src/index.css, src/pages/main/main.page.tsx, src/router/mainRouter.tsx
📌 **작업 내용**
컨테이너, max-width, nav bar 위치 등 레이아웃 설정했습니다.
=> Design: 전체 레이아웃 설정

src/components/common/button/Button.tsx, src/index.css, src/pages/main/main.page.tsx, tailwind.config.js
📌 **작업 내용**
피그마의 디자인시스템대로 컬러(primary, gray계열), 타이포 설정했습니다
📌 **확인 사항**
이후 전달받는 디자인에서 재사용되는 요소들 계속 추가해주세요
=> Design: 디자인시스템 컬러, 타이포 설정

src/@types/review.types.ts, src/api/auth.ts, src/api/comments.ts, src/api/review.ts, src/api/tours.ts, src/mocks/handlers.ts
📌 **작업 내용**
API 변경사항 적용 했습니다
📌 **확인 사항**
각자 맡은 api 수정사항 스웨거로 크로스체크 부탁드립니닷!
=> Feat: API 변경사항 적용

src/api/auth.ts, src/api/category.ts, src/api/client.ts, src/api/comments.ts, src/api/member.ts, src/api/region.ts, src/api/review.ts, src/api/tours.ts, src/api/trips.ts, src/mocks/handlers.ts
📌 **작업 내용**
데미데이터 약간 수정했습니다.
api 함수 내부에서 client 반복적으로 선언하는거 하나의 파일에서 임포트하는 방식으로 변경했습니다.
📌 **확인 사항**
=> Feat: Clients.ts 설정, 더미데이터 수정

package-lock.json, src/components/DetailSectionTop/DetailSectionTop.tsx, src/components/DetailSectionTop/DetailToursMap.tsx, src/components/DetailSectionTop/index.tsx, src/pages/detail/detail.page.tsx
📌 **작업 내용**
파일명, 스타일 수정
📌 **확인 사항**
=> refactor: 스타일 수정

src/components/DetailSectionTop/DetailToursButtons.tsx, src/components/DetailSectionTop/DetailToursMap.tsx
📌 **작업 내용**
컴포넌트 넓이, 높이 반응형 대응
📌 **확인 사항**
=> Style: 디테일 페이지 width, height 수정

package.json, pnpm-lock.yaml, src/components/DetailSectionBottom/DetailReview.tsx, src/components/DetailSectionBottom/DetailSectionBottom.tsx, src/components/DetailSectionBottom/ReviewItem.tsx, src/components/DetailSectionBottom/index.tsx, src/components/Review/ReviewRating.tsx, src/main.tsx, src/mocks/browser.ts, src/mocks/handlers.ts
📌 **작업 내용**
Env: 배포오류수정
📌 **확인 사항**
=> Env: 배포오류수정

src/utils/user/validationList.ts
=> Design: 누락된 리스트 추가

.github/workflows/preview.yaml, .github/workflows/production.yaml
📌 **작업 내용**
Deploy: preview 설정
📌 **확인 사항**
=> Deploy: preview 설정

.github/workflows/preview.yaml
=> Deploy: yaml 파일 수정

.github/workflows/preview.yaml, .github/workflows/production.yaml
=> 배포 프리뷰 테스트

.github/workflows/production.yaml
=> production test

src/api/client.ts, src/components/user/useInputBox/UserInputBox.tsx, src/pages/signin/signin.page.tsx
=> Feat: 로그인 임시 구현

src/components/common/icons/Icons.tsx, src/components/search/SearchInput.tsx, tailwind.config.js
📌 **작업 내용**
아이콘 경로 변경에 대응했습니다
📌 **확인 사항**
=> Hotfix: 검색창 아이콘 레이아웃 수정

vercel.json
📌 **작업 내용**
Env: vercel.json 추가
📌 **확인 사항**
=> Env: vercel.json 추가

package.json, pnpm-lock.yaml, src/components/Tours/ToursCategory.tsx, src/components/Tours/ToursCategoryItem.tsx, src/components/Tours/ToursSectionTop.tsx
📌 **작업 내용**
* Feat: 인기 지역 카테고리 swiper 적용
=> Feat: 인기 지역 카테고리 swiper 적용

package-lock.json, package.json, src/api/tours.ts, src/components/DetailSectionBottom/DetailReviews.tsx, src/components/DetailSectionTop/DetailToursInfo.tsx, src/components/DetailSectionTop/DetailToursMap.tsx, src/components/DetailSectionTop/DetailToursRating.tsx, src/components/DetailSectionTop/index.tsx, src/components/common/icons/Icons.tsx
📌 **작업 내용**
* 상세 페이지 관심 상품 등록 및 삭제 기능 추가
* 리뷰 괄호 추가
* 별점 클릭시 리뷰 컴포넌트로 스크롤 이동 추가
📌 **확인 사항**
=> Feat: QA 기반 수정 및 추가

src/components/DetailSectionTop/DetailToursInfo.tsx
📌 **작업 내용**
Feat: 좋아요 기능 구현 완료
📌 **확인 사항**
=> Feat: 좋아요 기능 구현 완료

index.html, src/components/search/RegionSelect.tsx, src/components/search/ResultCategory.tsx, src/components/search/SearchInput.tsx, src/components/search/SearchResult.tsx, src/pages/search/search.page.tsx
📌 **작업 내용**
- Feat: 모바일환경 auto zoom 비활성화 
- Fix: 뒤로가기 경로 수정 
- Fix: 마지막 검색결과 대응 - 버튼 숨김 및 메세지 
- Feat: 데이터 로딩중 버튼 상태 변경
- Feat: 검색창 오토포커스
📌 **확인 사항**
=> 검색기능 QA 대응

src/components/DetailSectionBottom/DetailReviews.tsx, src/components/Review/Review.tsx, src/components/common/modal/children/DeleteAlert.tsx, src/components/common/toastpopup/ToastPopUp.tsx, src/recoil/review.ts
📌 **작업 내용**
- 토스트 팝업으로 이름 수정
📌 **확인 사항**
=> Rename: 토스트 팝업으로 이름 수정

src/components/Auth/KakaoLoginButton.tsx
=> Refactor: 카카오 회원가입 버튼 <button> -> <a>로 수정

src/@types/tours.types.ts, src/api/member.ts, src/components/DetailSectionTop/DetailToursMap.tsx, src/components/Wish/Wish.tsx, src/components/Wish/WishCategory.tsx, src/components/Wish/WishCategoryItem.tsx, src/components/Wish/WishItem.tsx, src/components/Wish/WishList.tsx, src/components/common/like/Like.tsx, src/components/common/nav/Nav.tsx, src/pages/wishList/wishList.page.tsx, src/router/mainRouter.tsx
📌 **작업 내용**
* 나의 관심 여행지 페이지
* 맵 마커 이미지 기본값 변경
📌 **확인 사항**
=> Feat: 마이페이지/나의관심여행지 구현 완료

package.json, pnpm-lock.yaml, src/api/trips.ts, src/components/DetailSectionBottom/DetailReviewStats.tsx, src/components/common/accordion/Accordion.tsx, src/components/common/icons/Icons.tsx, src/index.css
📌 **작업 내용**
Feat: 아코디언 공통컴포넌트 구현, 이런점이 좋았어요 count 레이아웃 리펙토링, 여정 API 추가
📌 **확인 사항**
=> Feat: 아코디언 공통컴포넌트 구현, 이런점이 좋았어요 count 레이아웃 리펙토링, 여정 API 추가

src/components/Wish/Wish.tsx, src/components/common/noData/NoDataMessage.tsx
📌 **작업 내용**
마이관심여행지 데이터 없을시(찜 아이템 없을시) 컴포넌트 추가
📌 **확인 사항**
common > noData > noDataMessage 컴포넌트 사용 하면 될듯합니다.
=> Feat: 마이관심여행지 데이터 없을시 컴포넌트

src/components/Mypage/MypageInfo.tsx, src/components/Mypage/MypageItem.tsx, src/components/Mypage/MypageList.tsx, src/components/common/icons/Icons.tsx, src/components/common/nav/Nav.tsx, src/pages/mypage/editPassword.page.tsx, src/pages/mypage/editUserInfo.page.tsx, src/pages/mypage/editUserSurvey.page.tsx, src/pages/mypage/index.ts, src/pages/mypage/mypage.page.tsx, src/router/mainRouter.tsx
=> Fe 56  feat/new user/mypage

src/components/common/alert/Alert.tsx, src/components/common/like/Like.tsx, src/components/common/nav/Nav.tsx, src/pages/wishList/wishList.page.tsx
📌 **작업 내용**
* 관심 여행지 등록 및 삭제 기능 : 비로그인 유저 알럿 처리
* 관심 여행지 조회 기능 : 비로그인 유저 알럿 처리
* navigate : siginin => login 으로 변경
📌 **확인 사항**
마이페이지 - 관심 여행지 등록 작업 끝
=> Refactor: 비로그인 유저 알럿 처리

src/@types/member.types.ts, src/api/member.ts, src/components/Auth/AuthInput/AuthInputBox/AuthCurrentPwInputBox.tsx, src/components/Auth/AuthInput/AuthInputBox/AuthEmailInputBox.tsx, src/components/Auth/AuthSurvey/AuthSurvey.tsx, src/components/Auth/AuthSurvey/AuthSurveyOption.tsx, src/components/DetailSectionTop/DetailToursMap.tsx, src/components/common/BackBox/BackBox.tsx, src/components/common/icons/Icons.tsx, src/pages/signup/signupSurvey.page.tsx, src/utils/survey.constants.ts
=> Fe 20  feat/new user/new signup

src/components/common/icons/Icons.tsx, src/pages/signup/signupSuccess.page.tsx
=> Design: 회원가입 완료 페이지 구현

src/api/authClient.ts, src/api/client.ts, src/components/Mypage/DeleteMemberButton.tsx, src/components/common/BackBox/BackBox.tsx, src/pages/mypage/editUserInfo.page.tsx
📌 **작업 내용**
- 회원 탈퇴 구현
- 비빌번호 수정 버튼 생성
- 리프에시 토큰 저장 안되는 문제 해결
=> Fix: 리프레시 저장 문제 해결

src/components/DetailSectionTop/DetailTopButton.tsx, src/components/Review/ReviewComments.tsx, src/components/common/nav/InputComment.tsx, src/pages/detail/detail.page.tsx, src/pages/reviewComment/reviewComment.page.tsx
📌 **작업 내용**
- 이벤트버블링, 여백 등 때문에 스크롤버튼 설정하다가 다시 만드는게 나을거같아서 주석처리
- 댓글 입력창 재설정
- 
📌 **확인 사항**
=> Fe 79  feat/mypage review

src/@types/member.types.ts, src/api/authClient.ts, src/api/client.ts, src/components/Auth/Login/AuthButtons/KakaoLoginButton.tsx, src/components/Auth/Login/KakaoLogin.tsx, src/components/Auth/Login/index.ts, src/pages/login/loginKakao.page.tsx, src/pages/signup/signupInfo.page.tsx
=> Fe 21  feat/new user/new signin

src/components/Auth/Login/KakaoLogin.tsx
📌 **작업 내용**
- 카카오 로그인 회원가입 여부 판단 수정
=> Refactor: 카카오 로그인 회원가입 여부 판단 수정

src/components/DetailSectionTop/DetailToursButtons.tsx, src/components/common/nav/InputComment.tsx
=> Refactor: 로그인 판별 localstorage에서 api response로 변경

src/@types/trips.types.ts, src/components/MyTrip/CreateMyTripButton.tsx, src/components/MyTrip/MyTrip.tsx, src/components/MyTrip/MyTripItem.tsx, src/components/MyTrip/MyTripList.tsx, src/components/Wish/Wish.tsx, src/pages/myTrip/myTrip.page.tsx
📌 **작업 내용**
Refactor: 빌드 에러 및 여정 생성 버튼
📌 **확인 사항**
=> Refactor: 빌드 에러 및 여정 생성 버튼

src/@types/auth.types.ts, src/components/Auth/AuthSurvey/AuthSurvey.tsx, src/components/Auth/AuthSurvey/AuthSurveyOption.tsx, src/components/Mypage/LogoutButton.tsx, src/components/Mypage/MypageItem.tsx, src/components/common/icons/Icons.tsx, src/pages/signup/signup.page.tsx
📌 **작업 내용**
- 이용약관 추가
- 여행 취향 모두 선택 or 건너뛰기 적용
- 로그아웃 후 홈으로 이동
- 모달 클릭 후 로그인 페이지로 이동
=> 이용약관 추가 / QA 수정

src/@types/trips.types.ts, src/api/member.ts, src/api/trips.ts, src/components/DatePicker/Calendar.tsx, src/hooks/useCounter.ts, src/pages/create/createTrip.page.tsx, src/utils/formatDate.ts
📌 **작업 내용**
- 가지고 있는 여정 갯수 확인 후 디폴트 타이틀에 반영 
- 여정 생성 api 연동 
- 생성 성공 후 /trip/:id 로 이동 
- 캘린더 스타일 수정
📌 **확인 사항**
getMemberTrips의 파라미터 기본 값을 설정했습니다.
=> 나의 여정 생성 api 연동 완료 

src/@types/socket.types.ts, src/api/socket.ts, src/recoil/socket.ts
📌 **작업 내용**
Feat: 소켓 명세 변경사항 반영
📌 **확인 사항**
=> Feat: 소켓 명세 변경사항 반영

src/@types/service.ts, src/@types/socket.types.ts, src/api/socket.ts, src/components/Plan/PlanItemBox.tsx, src/recoil/socket.ts
📌 **작업 내용**
여행 아이템 방문 교통수단 각 아이템 별 변경가능 -> 날짜별 교통 수단 변경으로 수정
- 여행 아이템 방문 교통 수단 변경 이벤트 발생시 삭제
- 여행 날짜별 교통 수단 변경 이벤트 발생시 추가
- 방문수단 변경 관련해서 pub 응답데이터 변경
📌 **확인 사항**
=> Fix: 소켓 api 변경사항 적용

src/api/trips.ts, src/components/common/button/ListSelectBtn.tsx, src/pages/plan/OurLikedList.tsx, src/pages/plan/addPlace/AddtoListBtn.tsx, src/pages/plan/addPlace/MyLiked.tsx, src/pages/plan/addPlace/MyLikedList.tsx, src/pages/plan/addPlace/MyLikedListItem.tsx, src/pages/plan/addPlace/PlanAddPlace.page.tsx, src/pages/plan/addPlace/ResultCategoryPlan.tsx, src/pages/plan/addPlace/ResultItem.tsx, src/pages/plan/addPlace/SearchResult.tsx, src/pages/plan/planPlaceTrip.page.tsx, src/pages/trip/AddOurList.tsx, src/recoil/listItem.ts, src/router/socketRouter.tsx
📌 **작업 내용**
- 우리의 관심목록 추가를 위한 내 관심목록과 검색결과 페칭
- 우리의 관심목록에 post 연동
📌 **확인 사항**
/trip/:id/add 에서 확인할 수 있습니다.
=> Fe 69  feat/create/where when

src/components/Plan/PlanSchedule.tsx, src/components/Plan/PlanSectionTop.tsx
=> 계획 정보 소켓 연결

src/@types/service.ts, src/@types/socket.types.ts, src/@types/trips.types.ts, src/api/socket.ts, src/api/trips.ts, src/components/DetailSectionTop/DetailAddSchedule.tsx, src/components/MyTrip/MyTripItem.tsx, src/components/Plan/PlanEditItemBox.tsx, src/components/Plan/PlanItem.tsx, src/components/Plan/PlanMoveItem.tsx, src/components/Plan/PlanSectionTop.tsx, src/components/Plan/TripBudget.tsx, src/components/Trip/EditCodeModal.tsx, src/components/Trip/LikedToursList.tsx, src/components/Trip/LikedToursLists/LikedToursListBox.tsx, src/components/Trip/LikedToursLists/LikedToursListItem.tsx, src/components/Trip/TripRealtimeEditor.tsx, src/components/Trip/TripSchedule.tsx, src/components/Trip/TripSectionTop.tsx, src/hooks/useGetTripsAuthority.ts, src/hooks/useSocket.ts, src/pages/plan/AddToTripPlan/OurLiked.tsx, src/pages/plan/addToOurPlace/AddtoListBtn.tsx, src/pages/plan/addToOurPlace/MyLiked.tsx, src/pages/plan/addToOurPlace/SearchResult.tsx, src/pages/share/shareCode.page.tsx, src/pages/trip/AddOurList.page.tsx, src/recoil/socket.ts, src/router/socketRouter.tsx
📌 **작업 내용**
Refactor: 여정페이지 리펙토링
📌 **확인 사항**
=> Refactor: 여정페이지 리펙토링

src/components/Plan/PlanItemBox.tsx, src/components/Trip/TripPreference.tsx, src/pages/mypage/editUserSurvey.page.tsx
📌 **작업 내용**
Feat: 내 여행취향 설정하러가기 구현
📌 **확인 사항**
=> Feat: 내 여행취향 설정하러가기 구현

src/components/Plan/PlanSchedule.tsx, src/components/Plan/TripMap.tsx, src/components/Trip/EditCodeModal.tsx
📌 **작업 내용**
* 여정페이지 장소 없을 때 default로 대한민국 지도 보이기 설정
* 계획 스케줄 날짜 형식에 맞게 변환
* 여정 편집 모달 width 재설정
📌 **확인 사항**
=> 여정 지도 default 설정

src/components/Plan/PlanSectionTop.tsx, src/components/Trip/TripPreference.tsx, src/components/Trip/TripRealtimeMember.tsx, src/components/common/tab/Tab.tsx, src/pages/plan/addToOurPlace/AddtoListBtn.tsx, src/utils/calculatePercentage.ts
📌 **작업 내용**
- 여행취향 디폴트 디자인 구현 및 디버깅
📌 **확인 사항**
=> Fix: 여행취향 디폴트 디자인 구현 및 디버깅

src/components/Trip/TripSectionTop.tsx, src/hooks/useGetTripsAuthority.ts
📌 **작업 내용**
여정 편집 가능 여부 판단 로직 수정
=> Refactor: 여정 편집 상태 판단 수정

src/components/Plan/TripBudget.tsx, src/components/Tours/ToursCategory.tsx, src/components/Tours/ToursCategoryItem.tsx, src/components/Tours/ToursCategoryItemSkeleton.tsx, src/components/Tours/ToursItem.tsx, src/components/Trip/EditCodeModal.tsx, src/components/common/nav/Nav.tsx, src/components/common/tab/Tab.tsx, src/pages/trip/tripEdit.page.tsx
📌 **작업 내용**
* 경비 수정 모달 input width 재설정
* 탭 리스트 가로 스크롤 추가
* 여정 날짜 변경 시 날짜 밀리는 에러 해결
* 메인페이지 디자인 QA 반영
=> QA: 여정페이지 / 메인페이지 디자인

src/components/Trip/EditCodeModal.tsx
=> 여정 나가기 텍스트 변경

src/pages/create/createTrip.page.tsx, src/router/routerLayout.tsx
📌 **작업 내용**
화면 높이 설정을 수정했습니다
📌 **확인 사항**
=> Fix: nav 위치 수정

src/components/DetailSectionTop/DetailAddSchedule.tsx, src/components/Plan/PlanMoveItem.tsx
📌 **작업 내용**
Fix: 바텀시트 반응형 적용(양옆짤림 해결)
📌 **확인 사항**
=> Fix: 바텀시트 반응형 적용(양옆짤림 해결)

src/components/Auth/AuthSurvey/AuthSurvey.tsx, src/components/Share/IsEditableModal.tsx, src/pages/mypage/editUserSurvey.page.tsx
📌 **작업 내용**
- 바텀 시트 넓이 수정
- 여행 취향 수정 후 경로 변경
=> Refactor: 여정 QA 적용

src/router/mainRouter.tsx, src/router/routerLayout.tsx
📌 **작업 내용**
여정 QA - 여정 취향 기존 설정 표시 개선
=> Refactor: 유저 정보 조회 위치 수정

src/pages/trip/tripEdit.page.tsx
📌 **작업 내용**
* 여정 수정 페이지 button 위치 조정
* 여정 수정 페이지 input 밀림 조정
=> 여정 수정 페이지 QA 반영

src/components/Review/ReviewButton.tsx, src/components/common/modal/children/MyAlert.tsx
=> Fix: 버튼 높이 변경

src/components/Trip/PlanTripButton.tsx, src/components/Trip/TripPreference.tsx
=> Fix: 비로그인/권한x 시, 여행취향설정버튼 비활성화

src/components/Trip/LikedToursLists/LikedToursListItem.tsx
📌 **작업 내용**
우리의관심여행지 - 투표 취소 기능 추가
=> QA: 우리의관심여행지 - 투표 취소 기능 추가

src/components/Plan/PlanItemBox.tsx
=> 경로 시간 포맷팅 추가

src/router/routerLayout.tsx
=> 여정 수정페이지 nav 제거

index.html
=> Refactor: GA 적용

index.html, src/@types/detail.types.ts, src/@types/review.types.ts, src/@types/tours.types.ts, src/@types/trips.types.ts, src/api/review.ts, src/components/DetailSectionBottom/DetailReviews.tsx, src/components/DetailSectionBottom/ReviewItem.tsx, src/components/DetailSectionTop/DetailToursButtons.tsx, src/components/Review/CommentItem.tsx, src/components/Review/MyReview.tsx, src/components/Review/Review.tsx, src/components/Review/ReviewButton.tsx, src/components/Review/ReviewComments.tsx, src/components/Review/ReviewKeyword.tsx, src/components/Review/ReviewRating.tsx, src/components/Trip/TripInfo.tsx, src/components/Trip/TripParticipant.tsx, src/components/Trip/TripPreference.tsx, src/components/Trip/TripRealtimeMember.tsx, src/components/common/modal/Modal.tsx, src/components/common/toastpopup/ToastPopUp.tsx, src/recoil/review.ts
📌 **작업 내용**
- any 타입 개선
- 전체 워딩 개선
📌 **확인 사항**
=> Fe 102  feat/refactor

index.html
=> Refactor: GA 적용2

src/components/MyTrip/MyTripIngItem.tsx, src/components/MyTrip/MyTripItem.tsx, src/components/common/nav/Nav.tsx
=> Fix: 나의 여정 간격 수정

src/components/Auth/AuthInput/AuthInputBox/AuthInputItem/AuthInput.tsx, src/components/Auth/AuthSurvey/AuthSurvey.tsx, src/components/Auth/SignupInfo/AuthDropDown/AuthDropDown.tsx, src/components/Auth/SignupInfo/AuthDropDown/AuthDropDownOption.tsx, src/components/Auth/SignupInfo/SignupInfoForm.tsx, src/components/Mypage/UserInfoForm.tsx, src/components/common/BackBox/BackBox.tsx, src/components/common/icons/Icons.tsx, src/pages/mypage/editUserInfo.page.tsx, src/pages/mypage/editUserSurvey.page.tsx, src/pages/signup/signup.page.tsx, src/pages/signup/signupSuccess.page.tsx, src/pages/signup/signupSurvey.page.tsx, src/utils/authSelectOptions.ts
📌 **작업 내용**
- 드롭다운 퍼블리싱
- 저장 버튼이 없고 회원가입 시 있었던 완료 버튼이 있음 해결
- 완료 버튼 위에 회색 여백 생김
- 회원가입 완료 버튼 이동
- 뒤로 가기 아이콘 수정
=> Refactor: 마이페이지 디자인 QA 적용

src/components/Plan/PlanEditItemBox.tsx, src/components/Plan/PlanMoveItem.tsx
📌 **작업 내용**
Fix: 디자인 qa 반영
📌 **확인 사항**
=> Fix: 디자인 qa 반영
